collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2688172
color:
  saturation: 0.3446418
  brandStrength: 0.2007169
  lightness: 0.4711395
  brandColors:
    - '#FFFFFC'
    - '#0F0D16'
    - '#2F166E'
    - '#AC6E65'
    - '#EAA29A'
  rhythmicContrast: 0.0183254
layout_spectrum: 1
name: Camryn
